In [2]:
import pandas as pd
df = pd.read_csv(r'C:\Users\HP\Desktop\waste-main\waste-main\example.csv')
print(df)

       id first_name      last_name                           email  gender  \
0       1     Joseph      Zaniolini  jzaniolini0@simplemachines.org    Male
1       2     Freida  Drillingcourt       fdrillingcourt1@umich.edu  Female
2       3      Nanni         Herity        nherity2@statcounter.com  Female
3       4     Orazio       Frayling        ofrayling3@economist.com    Male
4       5   Julianne       Murrison         jmurrison4@cbslocal.com  Female
..    ...        ...            ...                             ...     ...
995   996   Parrnell           Jeff             pjeffrn@4shared.com    Male
996   997        Pat       Warstall         pwarstallro@dropbox.com    Male
997   998     Willyt     Vannuccini     wvannuccinirp@tuttocitta.it  Female
998   999     Gaelan     Petrashkov     gpetrashkovrq@hostgator.com    Male
999  1000   Stirling       Francesc     sfrancescrr@cyberchimps.com    Male

         ip_address                   city
0    163.168.68.132         Pedro Leopoldo
1     97.212.102.79                   Buri
2    145.151.178.98                 Claver
3    25.199.143.143                 Kungur
4    10.186.243.144  Sainte-Luce-sur-Loire
..              ...                    ...
995    159.55.55.39                 Dengok
996   169.200.7.131         Rosário do Sul
997  156.149.18.155             Xiaopingba
998  219.109.169.75              Bethlehem
999   108.193.9.206            Potok Złoty

[1000 rows x 7 columns]

In [16]:
df_1 = df[(df['gender'] == 'Male')]
df_1

,id,first_name,last_name,email,gender,ip_address,city
0,1,Joseph,Zaniolini,jzaniolini0@simplemachines.org,Male,163.168.68.132,Pedro Leopoldo
3,4,Orazio,Frayling,ofrayling3@economist.com,Male,25.199.143.143,Kungur
8,9,Chrissy,Hedworth,chedworth8@china.com.cn,Male,124.222.93.57,Boevange-sur-Attert
9,10,Hyatt,Gasquoine,hgasquoine9@google.ru,Male,221.155.106.39,Złoty Stok
11,12,Andrew,Bath,abathb@umn.edu,Male,64.36.30.186,El Hermel
...,...,...,...,...,...,...,...
994,995,Glynn,Wakerley,gwakerleyrm@disqus.com,Male,10.67.24.104,Rennes
995,996,Parrnell,Jeff,pjeffrn@4shared.com,Male,159.55.55.39,Dengok
996,997,Pat,Warstall,pwarstallro@dropbox.com,Male,169.200.7.131,Rosário do Sul
998,999,Gaelan,Petrashkov,gpetrashkovrq@hostgator.com,Male,219.109.169.75,Bethlehem
999,1000,Stirling,Francesc,sfrancescrr@cyberchimps.com,Male,108.193.9.206,Potok Złoty

In [18]:
df_2 = df_1[['first_name', 'last_name']]
df_2

    first_name   last_name
0       Joseph   Zaniolini
3       Orazio    Frayling
8      Chrissy    Hedworth
9        Hyatt   Gasquoine
11      Andrew        Bath
..         ...         ...
994      Glynn    Wakerley
995   Parrnell        Jeff
996        Pat    Warstall
998     Gaelan  Petrashkov
999   Stirling    Francesc

[486 rows x 2 columns]

In [21]:
df_3 = df[(df.city== "Claver") | (df['city'] == 'Buri')]
df_3

,id,first_name,last_name,email,gender,ip_address,city
1,2,Freida,Drillingcourt,fdrillingcourt1@umich.edu,Female,97.212.102.79,Buri
2,3,Nanni,Herity,nherity2@statcounter.com,Female,145.151.178.98,Claver

In [24]:
df_4 = df[df.first_name.str.startswith('S')]
df_4

,id,first_name,last_name,email,gender,ip_address,city
24,25,Sarina,Choulerton,schoulertono@wisc.edu,Female,73.36.0.165,Íquira
31,32,Sutherlan,Mundee,smundeev@nsw.gov.au,Male,68.91.169.230,Keluke
50,51,Salvidor,Cawthry,scawthry1e@youtu.be,Male,68.84.121.114,Habartov
66,67,Salomi,Pinnock,spinnock1u@hc360.com,Female,20.234.128.32,Venda
69,70,Stormie,Dougal,sdougal1x@cbc.ca,Female,63.157.30.92,Woniuhe
83,84,Sigmund,Sessions,ssessions2b@bizjournals.com,Male,218.191.236.117,Bordeaux
91,92,Skelly,Cragg,scragg2j@naver.com,Male,58.82.80.21,Wang Saphung
107,108,Susi,Pawsey,spawsey2z@zimbio.com,Female,164.219.128.94,Couço
136,137,Silva,Pittham,spittham3s@ibm.com,Female,18.77.14.20,Rayevskiy
197,198,Sanson,Ramelot,sramelot5h@smugmug.com,Male,207.245.213.229,Mercedes
211,212,Sibilla,Stachini,sstachini5v@dyndns.org,Female,66.219.114.10,Rio Grande da Serra
234,235,Shep,Voyce,svoyce6i@linkedin.com,Male,253.119.174.230,Kumanis
256,257,Shoshanna,Stollsteimer,sstollsteimer74@mysql.com,Female,59.129.39.60,Az Zuwaytīnah
264,265,Saundra,Butterfint,sbutterfint7c@redcross.org,Male,34.0.120.48,Sincelejo
266,267,Shaughn,Antoniades,santoniades7e@salon.com,Male,81.81.69.245,Lumphăt
285,286,Sibilla,Alesi,salesi7x@chron.com,Female,54.24.9.225,Xingou
304,305,Stavros,McGeady,smcgeady8g@disqus.com,Male,135.200.148.69,Aketi
330,331,Sydel,Sherland,ssherland96@de.vu,Female,45.27.130.2,Santana do Paraíso
342,343,Stephenie,Hurt,shurt9i@goo.gl,Female,215.144.121.249,Zharkent
343,344,Sergei,Blumson,sblumson9j@yelp.com,Male,98.24.92.125,Daping
352,353,Simone,McMychem,smcmychem9s@ow.ly,Female,185.172.219.152,Sieradza
358,359,Saudra,McGrill,smcgrill9y@ocn.ne.jp,Female,255.236.14.201,Pombas
389,390,Stephi,Miskimmon,smiskimmonat@vimeo.com,Female,158.67.131.220,Arrap’i
411,412,Salomone,Arsey,sarseybf@newyorker.com,Male,36.145.122.195,Gorobinci
416,417,Sayer,Derks,sderksbk@netvibes.com,Male,211.137.204.125,Tayang
424,425,Saxe,Hegdonne,shegdonnebs@wufoo.com,Male,82.60.153.78,Wichit
436,437,Sib,Chavey,schaveyc4@deviantart.com,Female,67.17.36.69,Kotlovka
447,448,Sidonnie,Ianelli,sianellicf@edublogs.org,Female,105.14.138.208,Luopioinen
457,458,Sauveur,Povele,spovelecp@taobao.com,Male,52.191.202.161,Nangalisan
468,469,Susann,Sciusscietto,ssciussciettod0@topsy.com,Female,117.204.19.108,Dayangqi
472,473,Skippie,Obern,sobernd4@eventbrite.com,Male,196.57.252.103,Chaoyang
501,502,Sabine,Lyosik,slyosikdx@360.cn,Female,161.232.137.136,Bayt ‘Īnūn
526,527,Shurwood,Sisneros,ssisnerosem@cnbc.com,Male,208.151.194.106,Pamatang
542,543,Stormi,Schimke,sschimkef2@apple.com,Female,133.116.215.131,Yonghe
619,620,Stafani,Boggish,sboggishh7@ox.ac.uk,Female,215.78.129.133,Frederico Westphalen
637,638,Suzann,Hugli,shuglihp@engadget.com,Female,251.197.224.18,Banjar Jambe Baleran
661,662,Salvador,Daunter,sdaunterid@huffingtonpost.com,Male,155.85.251.25,El Rancho
725,726,Sutton,Jelk,sjelkk5@loc.gov,Male,124.77.233.209,Sanguinheira
750,751,Skipper,Naisbit,snaisbitku@tuttocitta.it,Male,254.42.37.151,Washington
754,755,Siegfried,Stewartson,sstewartsonky@studiopress.com,Male,199.139.87.87,Baykonyr
767,768,Skippy,Odell,sodelllb@goo.gl,Male,209.219.142.176,Émponas
772,773,Sherri,Runacres,srunacreslg@mail.ru,Female,115.28.145.171,San Gil
776,777,Simeon,Diloway,sdilowaylk@mozilla.com,Male,93.224.165.226,Changliang
780,781,Samara,Spall,sspalllo@yahoo.com,Female,188.21.28.134,Birowo
805,806,Shannah,Daudray,sdaudraymd@cyberchimps.com,Female,219.175.89.132,Tagdanua
830,831,Sonya,Clifft,sclifftn2@businesswire.com,Female,139.46.233.62,Saynshand
840,841,Sigismund,Barnish,sbarnishnc@twitter.com,Male,170.148.96.127,Izingolweni
845,846,Sherwin,Marriage,smarriagenh@devhub.com,Male,193.127.164.248,Weishan
850,851,Sibelle,Godfray,sgodfraynm@google.com.au,Female,178.39.99.237,Hato Mayor del Rey
857,858,Stanislaw,McClenan,smcclenannt@theguardian.com,Male,32.61.125.245,Poshnje
878,879,Sherman,Vaulkhard,svaulkhardoe@is.gd,Male,18.111.45.167,Jatipamor
951,952,Shena,Townshend,stownshendqf@livejournal.com,Female,53.15.203.106,Yong’an
955,956,Shurlock,Rubanenko,srubanenkoqj@narod.ru,Male,124.177.68.255,Jishi
959,960,Sioux,Smillie,ssmillieqn@so-net.ne.jp,Female,106.42.217.238,Nomhon
999,1000,Stirling,Francesc,sfrancescrr@cyberchimps.com,Male,108.193.9.206,Potok Złoty

In [25]:
df_5 = df_4[['email']]
df_5

                             email
24           schoulertono@wisc.edu
31             smundeev@nsw.gov.au
50             scawthry1e@youtu.be
66            spinnock1u@hc360.com
69                sdougal1x@cbc.ca
83     ssessions2b@bizjournals.com
91              scragg2j@naver.com
107           spawsey2z@zimbio.com
136             spittham3s@ibm.com
197         sramelot5h@smugmug.com
211         sstachini5v@dyndns.org
234          svoyce6i@linkedin.com
256      sstollsteimer74@mysql.com
264     sbutterfint7c@redcross.org
266        santoniades7e@salon.com
285             salesi7x@chron.com
304          smcgeady8g@disqus.com
330              ssherland96@de.vu
342                 shurt9i@goo.gl
343            sblumson9j@yelp.com
352              smcmychem9s@ow.ly
358           smcgrill9y@ocn.ne.jp
389         smiskimmonat@vimeo.com
411         sarseybf@newyorker.com
416          sderksbk@netvibes.com
424          shegdonnebs@wufoo.com
436       schaveyc4@deviantart.com
447        sianellicf@edublogs.org
457           spovelecp@taobao.com
468      ssciussciettod0@topsy.com
472        sobernd4@eventbrite.com
501               slyosikdx@360.cn
526           ssisnerosem@cnbc.com
542           sschimkef2@apple.com
619            sboggishh7@ox.ac.uk
637          shuglihp@engadget.com
661  sdaunterid@huffingtonpost.com
725                sjelkk5@loc.gov
750       snaisbitku@tuttocitta.it
754  sstewartsonky@studiopress.com
767                sodelllb@goo.gl
772            srunacreslg@mail.ru
776         sdilowaylk@mozilla.com
780             sspalllo@yahoo.com
805     sdaudraymd@cyberchimps.com
830     sclifftn2@businesswire.com
840         sbarnishnc@twitter.com
845         smarriagenh@devhub.com
850       sgodfraynm@google.com.au
857    smcclenannt@theguardian.com
878             svaulkhardoe@is.gd
951   stownshendqf@livejournal.com
955          srubanenkoqj@narod.ru
959        ssmillieqn@so-net.ne.jp
999    sfrancescrr@cyberchimps.com

In [27]:
df_6 = df[df.gender == "Female"]
df_7 = df_6[['last_name', 'city']]
df_7

         last_name                   city
1    Drillingcourt                   Buri
2           Herity                 Claver
4         Murrison  Sainte-Luce-sur-Loire
5            Gamet               Pak Phli
6           Howatt               Palmares
..             ...                    ...
983   Drew-Clifton                Guariba
989         Nilles          Sherwood Park
991      Sheavills              Thanatpin
992      Marvelley             Kleszczewo
997     Vannuccini             Xiaopingba

[514 rows x 2 columns]